jwt:
  secret: dfsdfsd9fsdifosid6f8sflsi
  lifetime: 30m

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-messages
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-messages

#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
