jwt:
  secret: dfsdfsd9fsdifosid6f8sflsi
  lifetime: 30m

spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nifi
    username: sp
    password: sp
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
