jwt:
  secret: dfsdfsd9fsdifosid6f8sflsi
  lifetime: 30m

spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=usermessages
      username: postgres
      password: root
  jpa:
      hibernate:
        ddl-auto:  create-drop # update
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect


#  security:
#    user:
#      name: user
#      password: user

#server:
#  port: 8080
#  servlet:
#    context-path: /usermessage

